/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationBookingIdRouteImport } from './routes/reservation.$bookingId'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationBookingIdRoute = ReservationBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => ReservationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/reservation/$bookingId': typeof ReservationBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/reservation/$bookingId': typeof ReservationBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/register': typeof RegisterRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/reservation/$bookingId': typeof ReservationBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/menu'
    | '/register'
    | '/reservation'
    | '/reservation/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/menu'
    | '/register'
    | '/reservation'
    | '/reservation/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/menu'
    | '/register'
    | '/reservation'
    | '/reservation/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  RegisterRoute: typeof RegisterRoute
  ReservationRoute: typeof ReservationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$bookingId': {
      id: '/reservation/$bookingId'
      path: '/$bookingId'
      fullPath: '/reservation/$bookingId'
      preLoaderRoute: typeof ReservationBookingIdRouteImport
      parentRoute: typeof ReservationRoute
    }
  }
}

interface ReservationRouteChildren {
  ReservationBookingIdRoute: typeof ReservationBookingIdRoute
}

const ReservationRouteChildren: ReservationRouteChildren = {
  ReservationBookingIdRoute: ReservationBookingIdRoute,
}

const ReservationRouteWithChildren = ReservationRoute._addFileChildren(
  ReservationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  RegisterRoute: RegisterRoute,
  ReservationRoute: ReservationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
